### ISSUE TITLE
There is an issue with CheckListSelectAllItem - it causes binding errors. Please provide a fix.

### ISSUE THREAD

**Issue by 9nix6** [SyncfusionExamples/wpf-checked-listbox-examples#1]
This can be reproduced by building and running the [CheckItem-By-Property](https://github.com/SyncfusionExamples/wpf-checked-listbox-examples/tree/master/Samples/CheckItem-By-Property) sample

System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='<null>' BindingExpression:Path=IsChecked; DataItem='ListSelectAll' (HashCode=24481406); target element is 'CheckListSelectAllItem' (Name=''); target property is 'IsChecked' (type 'Boolean')

System.Windows.Data Error: 40 : BindingExpression path error: 'IsChecked' property not found on 'object' ''CollectionViewGroupInternal' (HashCode=62110049)'. BindingExpression:Path=IsChecked; DataItem='CollectionViewGroupInternal' (HashCode=62110049); target element is '**CheckListGroupItem**' (Name=''); target property is 'IsChecked' (type 'Boolean')

**Comment by JeganRavichandran** [comment]
@9nix6 this issue is now resolved in https://github.com/SyncfusionExamples/wpf-checked-listbox-examples/pull/2
